//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfClient.Calc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Calc.ICalculator")]
    public interface ICalculator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Sum", ReplyAction="http://tempuri.org/ICalculator/SumResponse")]
        double Sum(double x, double Y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Sum", ReplyAction="http://tempuri.org/ICalculator/SumResponse")]
        System.Threading.Tasks.Task<double> SumAsync(double x, double Y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Sub", ReplyAction="http://tempuri.org/ICalculator/SubResponse")]
        double Sub(double x, double Y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Sub", ReplyAction="http://tempuri.org/ICalculator/SubResponse")]
        System.Threading.Tasks.Task<double> SubAsync(double x, double Y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Mul", ReplyAction="http://tempuri.org/ICalculator/MulResponse")]
        double Mul(double x, double Y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Mul", ReplyAction="http://tempuri.org/ICalculator/MulResponse")]
        System.Threading.Tasks.Task<double> MulAsync(double x, double Y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Div", ReplyAction="http://tempuri.org/ICalculator/DivResponse")]
        double Div(double x, double Y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Div", ReplyAction="http://tempuri.org/ICalculator/DivResponse")]
        System.Threading.Tasks.Task<double> DivAsync(double x, double Y);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculatorChannel : WpfClient.Calc.ICalculator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorClient : System.ServiceModel.ClientBase<WpfClient.Calc.ICalculator>, WpfClient.Calc.ICalculator {
        
        public CalculatorClient() {
        }
        
        public CalculatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Sum(double x, double Y) {
            return base.Channel.Sum(x, Y);
        }
        
        public System.Threading.Tasks.Task<double> SumAsync(double x, double Y) {
            return base.Channel.SumAsync(x, Y);
        }
        
        public double Sub(double x, double Y) {
            return base.Channel.Sub(x, Y);
        }
        
        public System.Threading.Tasks.Task<double> SubAsync(double x, double Y) {
            return base.Channel.SubAsync(x, Y);
        }
        
        public double Mul(double x, double Y) {
            return base.Channel.Mul(x, Y);
        }
        
        public System.Threading.Tasks.Task<double> MulAsync(double x, double Y) {
            return base.Channel.MulAsync(x, Y);
        }
        
        public double Div(double x, double Y) {
            return base.Channel.Div(x, Y);
        }
        
        public System.Threading.Tasks.Task<double> DivAsync(double x, double Y) {
            return base.Channel.DivAsync(x, Y);
        }
    }
}
